version: '3.8'

networks:
  shopdev_network:
    driver: bridge

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    networks:
      - shopdev_network
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/shopDEV?authSource=admin
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - RABBITMQ_URI=amqp://guest:12345@rabbitmq:5672
      - REDIS_CACHE_HOST=redis
      - IOREDIS_IS_ENABLED=true
    depends_on:
      - mongodb
      - elasticsearch
      - rabbitmq
      - redis

  mongodb:
    image: mongo:5.0
    container_name: shopdev_mongodb
    networks:
      - shopdev_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: shopdev_es
    networks:
      - shopdev_network
    environment:
      - node.name=shopdev_es
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: shopdev_kibana
    networks:
      - shopdev_network

    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopdev_rabbitmq
    networks:
      - shopdev_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: shopdev_redis
    networks:
      - shopdev_network
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  mongodata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
